### ISSUE TITLE
Query batching support

### ISSUE THREAD

**Issue by FranciscoMSM** [helfer/apollo-link-queue#1]
It would be great to add an option to query batching the queued requests, in this way we can assure the reports are getting executed sequentially, I mean transport level query batching, get all the requests that are queued and send an array of mutations to the server, any thoughs on this? 

I would be more than happy to help you figure it out something 👍

**Comment by helfer** [comment]
Hey @FranciscoMSM, I think it's a good idea to batch the requests. I think it should already happen automatically if you have a batching link like apollo-link-batch-http (or whatever it's called). When the queue is drained, all requests are made in the same tick, so you can even set the batching interval to the smallest possible value and all queries should get batched together.

Regarding adding batching to this link itself: that's actually not possible because this link is not a terminating link. Batching happens on the transport, so it needs to be done on a terminating link (the last link on the chain which sends the query over the transport and receives the response). Luckily we don't have to add batching to this link, because it should already work, and if it doesn't work yet, we can make some modifications to this link and apollo-link-batch, and if necessary make the two pass the necessary information between each other via the context of the queries that pass through them.

Does that make sense? 🙂

**Comment by FranciscoMSM** [comment]
Yes it does! I already tried batching but not with this requisite, it makes sense its supposed to work, I'll try that with your link, thanks for the quick reply ☺
