### ISSUE TITLE
Named queues and discard

### ISSUE THREAD

**Issue by jonaskello** [helfer/apollo-link-queue#4]
This link looks really interesting :-). I'm working on an app where the user can make several changes to data but the changes are only done locally in the client and not persisted to the server until the user hits a save button. I don't really like this model but it's the way the legacy app works so I'm required to do it this way.

So my scenario is not really offline but offline-ish. But it shares a lot of problems with offline. We could consider the user to be offline until he hits save, then he goes online. 

I've got an idea how to solve this. I'm thinking I could make mutations for every change with optimistic updates, the way you are supposed to with apollo (by writing to the store with writeQuery). But since the mutation should not happen until the user hits save, I need to delay them. So apollo-link-queue looks like a good fit :-). However in order to make it work I think I would need two more features:

1. Having named queues, for example if editing several documents, each document could have it's own named queue (using the document id for the queue name). The queue name could be sent in the context parameter. If there is no queue name then just let the mutation pass. The current close/open methods could set a default queue name instead. So instead of .close()/.open() you could do .defaultQueue("offline")/.defaultQueue().

2. Having the ability to discard all queued mutations. If the user presses cancel instead of save then the mutations should not be sent to the server at all. At this point it would be nice if the optimistic updates automatically got reverted too, not sure if this could work.

Not sure this would work though. Happy for any thoughts on this!

**Comment by helfer** [comment]
Hey @jonaskello, sorry for the slow reply here, I was on vacation for a while 🙂 

1 is definitely possible. I didn't anticipate this being necessary, but it sounds like it would kind of make sense for your use-case, if you want Apollo to handle all the optimism. You could check out helfer/apollo-link-debounce, where I already implemented multiple named queues for a different purpose.

2. Being able to clear a queue (or all queues) sounds pretty useful as well and should be really easy to do. As for cancelling the optimistic update in the store: I think it's best to keep the link separate from the store, but it would definitely be possible to build something on top of apollo client and this link to get exactly the kind of behavior that you want.

If you're still interested, I think there are a few PRs that could get us there:
1. Add an option to clear the queue, maybe call it `clear()`. Should be super-easy.
2. Take the implementation of multiple named queues from apollo-link-debounce and replace the single queue with it. Ideally it would be backwards-compatible, so that queries without specific key would end up in the generic queue, which is the one affected by `open()` and `close()`. Opening and closing specific queues could be done by calling `open(<qid>)` and `close(<qid>)` respectively. An `openAll()` and `closeAll()` sounds like it might be useful as well, but it might not be absolutely necessary.

Let me know if you're interested in working on it. If you make a PR, I'd be happy to review it and merge it.

**Comment by jonaskello** [comment]
Thanks for the reply! I actually forked this repo and did a link where you can cancel/discard operations etc. and it worked, the store was reverted etc.

However I found that queuing mutations did not work well because once I sent them to the server they would execute in parallel, which was not what I wanted :-). Also there was some other problems with updating the apollo store that I could not make work the way I wanted. So in the end I went with a redux+normalizr+request-graphql solution that give me more control over the optimism. Now I queue objects that represents single mutation fields instead and then compose them into a single single mutation when the user hits save (using alias to be able to have the same field multiple times). The GQL spec requires each field in a mutation to execute in sequence so that works well.

**Comment by damir-eco-surv** [comment]
@jonaskello did you open source this solution? what you described is literally what i need

**Comment by jonaskello** [comment]
@damir-eco-surv Not the whole solution but I ended up writing my own normalization library for graphql that is part of this solution. It is [open sourced here](https://www.npmjs.com/package/graphql-norm). There is also some [related packages](https://www.npmjs.com/package/graphql-norm#related-packages) available that too are part of this solution.
