### ISSUE TITLE
Handling concurrency conflicts

### ISSUE THREAD

**Issue by LFP6** [helfer/apollo-link-queue#5]
I'm curious if you've considered issues with concurrency. Per
https://github.com/apollographql/apollo-cache-asyncstorage/issues/6#issuecomment-358465996 and 
https://github.com/apollographql/apollo-link/issues/125#issuecomment-340341673

**Comment by helfer** [comment]
Resolving conflicts is not something the link can or should do in my opinion. It is up to the store and the business logic of your application. But since it's an interesting topic, I wrote down some thoughts anyway:

Handling resolution of conflicts is a pretty tricky issue, and there are no solutions for the general case. That is: the correct resolution of a conflict often depends on the use-case, and thus needs to be decided by the programmer. Usually there's a server involved, which serves as a single source of truth. If that's not the case, things get even more complicated, so let's ignore distributed scenarios with network partition etc. for now.

Here are some possible options:
1) First-come-first-serve: whichever mutation for a given piece of data the server sees first is the one that goes through. Subsequent mutations that don't causally follow the most recent mutation are rejected.
2) Last-one-wins: For simple updates (the U in CRUD), you could also let the last one win, which means you don't do any conflict resolution and just apply updates as they come in, regardless of whether they'll ovewrite a recent update. This may not always be acceptable UX, but sometimes it is.
3) Try to resolve the conflict on the server (given enough metadata): In some cases it's possible for the server to adjust a mutation to preserve its original intention. If you're interested in that, operational transform would be a good term to look up.
4) Use CRDTs (conflict-free replicated data types). CRDTs are pretty new, and there's not a lot of practical knowledge out there yet (they're an academic invention), but they're an interesting way to completely side-step the issue of resolving conflicts in some cases. The conflict resolution is basically built into the data type. CRDTs don't exist for every data type, so they're not a panacea, but if your application can work with the ones that do exist, they may be a fun way to write an app with great offline UX, if you're the adventurous type of programmer.
